/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "common.pb-c.h"
void   employee__init
                     (Employee         *message)
{
  static Employee init_value = EMPLOYEE__INIT;
  *message = init_value;
}
size_t employee__get_packed_size
                     (const Employee *message)
{
  assert(message->base.descriptor == &employee__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t employee__pack
                     (const Employee *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &employee__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t employee__pack_to_buffer
                     (const Employee *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &employee__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Employee *
       employee__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Employee *)
     protobuf_c_message_unpack (&employee__descriptor,
                                allocator, len, data);
}
void   employee__free_unpacked
                     (Employee *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &employee__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue employee__gender__enum_values_by_number[2] =
{
  { "MALE", "EMPLOYEE__GENDER__MALE", 0 },
  { "FEMALE", "EMPLOYEE__GENDER__FEMALE", 1 },
};
static const ProtobufCIntRange employee__gender__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex employee__gender__enum_values_by_name[2] =
{
  { "FEMALE", 1 },
  { "MALE", 0 },
};
const ProtobufCEnumDescriptor employee__gender__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Employee.Gender",
  "Gender",
  "Employee__Gender",
  "",
  2,
  employee__gender__enum_values_by_number,
  2,
  employee__gender__enum_values_by_name,
  1,
  employee__gender__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor employee__field_descriptors[7] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Employee, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Employee, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gender",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Employee, gender),
    &employee__gender__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "date_of_birth",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Employee, date_of_birth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_10_annual_salary",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Employee, last_10_annual_salary),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_10_annual_bonus",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Employee, last_10_annual_bonus),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_10_annual_sales",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Employee, last_10_annual_sales),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned employee__field_indices_by_name[] = {
  3,   /* field[3] = date_of_birth */
  2,   /* field[2] = gender */
  0,   /* field[0] = id */
  5,   /* field[5] = last_10_annual_bonus */
  4,   /* field[4] = last_10_annual_salary */
  6,   /* field[6] = last_10_annual_sales */
  1,   /* field[1] = name */
};
static const ProtobufCIntRange employee__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor employee__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Employee",
  "Employee",
  "Employee",
  "",
  sizeof(Employee),
  7,
  employee__field_descriptors,
  employee__field_indices_by_name,
  1,  employee__number_ranges,
  (ProtobufCMessageInit) employee__init,
  NULL,NULL,NULL    /* reserved[123] */
};
