/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: delete_req.proto */

#ifndef PROTOBUF_C_delete_5freq_2eproto__INCLUDED
#define PROTOBUF_C_delete_5freq_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _DeleteRequest DeleteRequest;


/* --- enums --- */


/* --- messages --- */

struct  _DeleteRequest
{
  ProtobufCMessage base;
  uint64_t id;
};
#define DELETE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&delete_request__descriptor) \
    , 0 }


/* DeleteRequest methods */
void   delete_request__init
                     (DeleteRequest         *message);
size_t delete_request__get_packed_size
                     (const DeleteRequest   *message);
size_t delete_request__pack
                     (const DeleteRequest   *message,
                      uint8_t             *out);
size_t delete_request__pack_to_buffer
                     (const DeleteRequest   *message,
                      ProtobufCBuffer     *buffer);
DeleteRequest *
       delete_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   delete_request__free_unpacked
                     (DeleteRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DeleteRequest_Closure)
                 (const DeleteRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor delete_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_delete_5freq_2eproto__INCLUDED */
