/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: delete_res.proto */

#ifndef PROTOBUF_C_delete_5fres_2eproto__INCLUDED
#define PROTOBUF_C_delete_5fres_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _DeleteResponse DeleteResponse;


/* --- enums --- */


/* --- messages --- */

struct  _DeleteResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean result;
};
#define DELETE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&delete_response__descriptor) \
    , 0 }


/* DeleteResponse methods */
void   delete_response__init
                     (DeleteResponse         *message);
size_t delete_response__get_packed_size
                     (const DeleteResponse   *message);
size_t delete_response__pack
                     (const DeleteResponse   *message,
                      uint8_t             *out);
size_t delete_response__pack_to_buffer
                     (const DeleteResponse   *message,
                      ProtobufCBuffer     *buffer);
DeleteResponse *
       delete_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   delete_response__free_unpacked
                     (DeleteResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DeleteResponse_Closure)
                 (const DeleteResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor delete_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_delete_5fres_2eproto__INCLUDED */
