/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: delete_res.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "delete_res.pb-c.h"
void   delete_response__init
                     (DeleteResponse         *message)
{
  static DeleteResponse init_value = DELETE_RESPONSE__INIT;
  *message = init_value;
}
size_t delete_response__get_packed_size
                     (const DeleteResponse *message)
{
  assert(message->base.descriptor == &delete_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t delete_response__pack
                     (const DeleteResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &delete_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t delete_response__pack_to_buffer
                     (const DeleteResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &delete_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeleteResponse *
       delete_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeleteResponse *)
     protobuf_c_message_unpack (&delete_response__descriptor,
                                allocator, len, data);
}
void   delete_response__free_unpacked
                     (DeleteResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &delete_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor delete_response__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DeleteResponse, result),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned delete_response__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange delete_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor delete_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeleteResponse",
  "DeleteResponse",
  "DeleteResponse",
  "",
  sizeof(DeleteResponse),
  1,
  delete_response__field_descriptors,
  delete_response__field_indices_by_name,
  1,  delete_response__number_ranges,
  (ProtobufCMessageInit) delete_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
