/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: insert_res.proto */

#ifndef PROTOBUF_C_insert_5fres_2eproto__INCLUDED
#define PROTOBUF_C_insert_5fres_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _InsertResponse InsertResponse;


/* --- enums --- */


/* --- messages --- */

struct  _InsertResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean result;
  char *result_msg;
};
#define INSERT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insert_response__descriptor) \
    , 0, NULL }


/* InsertResponse methods */
void   insert_response__init
                     (InsertResponse         *message);
size_t insert_response__get_packed_size
                     (const InsertResponse   *message);
size_t insert_response__pack
                     (const InsertResponse   *message,
                      uint8_t             *out);
size_t insert_response__pack_to_buffer
                     (const InsertResponse   *message,
                      ProtobufCBuffer     *buffer);
InsertResponse *
       insert_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insert_response__free_unpacked
                     (InsertResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*InsertResponse_Closure)
                 (const InsertResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insert_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_insert_5fres_2eproto__INCLUDED */
