/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: insert_req.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "insert_req.pb-c.h"
void   insert_request__init
                     (InsertRequest         *message)
{
  static InsertRequest init_value = INSERT_REQUEST__INIT;
  *message = init_value;
}
size_t insert_request__get_packed_size
                     (const InsertRequest *message)
{
  assert(message->base.descriptor == &insert_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t insert_request__pack
                     (const InsertRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &insert_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t insert_request__pack_to_buffer
                     (const InsertRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &insert_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InsertRequest *
       insert_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InsertRequest *)
     protobuf_c_message_unpack (&insert_request__descriptor,
                                allocator, len, data);
}
void   insert_request__free_unpacked
                     (InsertRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &insert_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor insert_request__field_descriptors[1] =
{
  {
    "employee",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(InsertRequest, employee),
    &employee__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned insert_request__field_indices_by_name[] = {
  0,   /* field[0] = employee */
};
static const ProtobufCIntRange insert_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor insert_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InsertRequest",
  "InsertRequest",
  "InsertRequest",
  "",
  sizeof(InsertRequest),
  1,
  insert_request__field_descriptors,
  insert_request__field_indices_by_name,
  1,  insert_request__number_ranges,
  (ProtobufCMessageInit) insert_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
