/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: insert_req.proto */

#ifndef PROTOBUF_C_insert_5freq_2eproto__INCLUDED
#define PROTOBUF_C_insert_5freq_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "common.pb-c.h"

typedef struct _InsertRequest InsertRequest;


/* --- enums --- */


/* --- messages --- */

struct  _InsertRequest
{
  ProtobufCMessage base;
  Employee *employee;
};
#define INSERT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&insert_request__descriptor) \
    , NULL }


/* InsertRequest methods */
void   insert_request__init
                     (InsertRequest         *message);
size_t insert_request__get_packed_size
                     (const InsertRequest   *message);
size_t insert_request__pack
                     (const InsertRequest   *message,
                      uint8_t             *out);
size_t insert_request__pack_to_buffer
                     (const InsertRequest   *message,
                      ProtobufCBuffer     *buffer);
InsertRequest *
       insert_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   insert_request__free_unpacked
                     (InsertRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*InsertRequest_Closure)
                 (const InsertRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor insert_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_insert_5freq_2eproto__INCLUDED */
