/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: query_by_id_req.proto */

#ifndef PROTOBUF_C_query_5fby_5fid_5freq_2eproto__INCLUDED
#define PROTOBUF_C_query_5fby_5fid_5freq_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _QueryByIdRequest QueryByIdRequest;


/* --- enums --- */


/* --- messages --- */

struct  _QueryByIdRequest
{
  ProtobufCMessage base;
  uint64_t id;
};
#define QUERY_BY_ID_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&query_by_id_request__descriptor) \
    , 0 }


/* QueryByIdRequest methods */
void   query_by_id_request__init
                     (QueryByIdRequest         *message);
size_t query_by_id_request__get_packed_size
                     (const QueryByIdRequest   *message);
size_t query_by_id_request__pack
                     (const QueryByIdRequest   *message,
                      uint8_t             *out);
size_t query_by_id_request__pack_to_buffer
                     (const QueryByIdRequest   *message,
                      ProtobufCBuffer     *buffer);
QueryByIdRequest *
       query_by_id_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   query_by_id_request__free_unpacked
                     (QueryByIdRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*QueryByIdRequest_Closure)
                 (const QueryByIdRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor query_by_id_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_query_5fby_5fid_5freq_2eproto__INCLUDED */
