/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: query_by_id_res.proto */

#ifndef PROTOBUF_C_query_5fby_5fid_5fres_2eproto__INCLUDED
#define PROTOBUF_C_query_5fby_5fid_5fres_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "common.pb-c.h"

typedef struct _QueryByIdResponse QueryByIdResponse;


/* --- enums --- */


/* --- messages --- */

struct  _QueryByIdResponse
{
  ProtobufCMessage base;
  Employee *employee;
};
#define QUERY_BY_ID_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&query_by_id_response__descriptor) \
    , NULL }


/* QueryByIdResponse methods */
void   query_by_id_response__init
                     (QueryByIdResponse         *message);
size_t query_by_id_response__get_packed_size
                     (const QueryByIdResponse   *message);
size_t query_by_id_response__pack
                     (const QueryByIdResponse   *message,
                      uint8_t             *out);
size_t query_by_id_response__pack_to_buffer
                     (const QueryByIdResponse   *message,
                      ProtobufCBuffer     *buffer);
QueryByIdResponse *
       query_by_id_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   query_by_id_response__free_unpacked
                     (QueryByIdResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*QueryByIdResponse_Closure)
                 (const QueryByIdResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor query_by_id_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_query_5fby_5fid_5fres_2eproto__INCLUDED */
