/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: query_by_compensation_range_req.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "query_by_compensation_range_req.pb-c.h"
void   query_by_compensation_range_request__init
                     (QueryByCompensationRangeRequest         *message)
{
  static QueryByCompensationRangeRequest init_value = QUERY_BY_COMPENSATION_RANGE_REQUEST__INIT;
  *message = init_value;
}
size_t query_by_compensation_range_request__get_packed_size
                     (const QueryByCompensationRangeRequest *message)
{
  assert(message->base.descriptor == &query_by_compensation_range_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query_by_compensation_range_request__pack
                     (const QueryByCompensationRangeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &query_by_compensation_range_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query_by_compensation_range_request__pack_to_buffer
                     (const QueryByCompensationRangeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &query_by_compensation_range_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QueryByCompensationRangeRequest *
       query_by_compensation_range_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QueryByCompensationRangeRequest *)
     protobuf_c_message_unpack (&query_by_compensation_range_request__descriptor,
                                allocator, len, data);
}
void   query_by_compensation_range_request__free_unpacked
                     (QueryByCompensationRangeRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &query_by_compensation_range_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor query_by_compensation_range_request__field_descriptors[2] =
{
  {
    "min",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(QueryByCompensationRangeRequest, min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(QueryByCompensationRangeRequest, max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query_by_compensation_range_request__field_indices_by_name[] = {
  1,   /* field[1] = max */
  0,   /* field[0] = min */
};
static const ProtobufCIntRange query_by_compensation_range_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor query_by_compensation_range_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "QueryByCompensationRangeRequest",
  "QueryByCompensationRangeRequest",
  "QueryByCompensationRangeRequest",
  "",
  sizeof(QueryByCompensationRangeRequest),
  2,
  query_by_compensation_range_request__field_descriptors,
  query_by_compensation_range_request__field_indices_by_name,
  1,  query_by_compensation_range_request__number_ranges,
  (ProtobufCMessageInit) query_by_compensation_range_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
