/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: query_by_id_req.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "query_by_id_req.pb-c.h"
void   query_by_id_request__init
                     (QueryByIdRequest         *message)
{
  static QueryByIdRequest init_value = QUERY_BY_ID_REQUEST__INIT;
  *message = init_value;
}
size_t query_by_id_request__get_packed_size
                     (const QueryByIdRequest *message)
{
  assert(message->base.descriptor == &query_by_id_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query_by_id_request__pack
                     (const QueryByIdRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &query_by_id_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query_by_id_request__pack_to_buffer
                     (const QueryByIdRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &query_by_id_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QueryByIdRequest *
       query_by_id_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QueryByIdRequest *)
     protobuf_c_message_unpack (&query_by_id_request__descriptor,
                                allocator, len, data);
}
void   query_by_id_request__free_unpacked
                     (QueryByIdRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &query_by_id_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor query_by_id_request__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(QueryByIdRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query_by_id_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange query_by_id_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor query_by_id_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "QueryByIdRequest",
  "QueryByIdRequest",
  "QueryByIdRequest",
  "",
  sizeof(QueryByIdRequest),
  1,
  query_by_id_request__field_descriptors,
  query_by_id_request__field_indices_by_name,
  1,  query_by_id_request__number_ranges,
  (ProtobufCMessageInit) query_by_id_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
