/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: query_by_id_res.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "query_by_id_res.pb-c.h"
void   query_by_id_response__init
                     (QueryByIdResponse         *message)
{
  static QueryByIdResponse init_value = QUERY_BY_ID_RESPONSE__INIT;
  *message = init_value;
}
size_t query_by_id_response__get_packed_size
                     (const QueryByIdResponse *message)
{
  assert(message->base.descriptor == &query_by_id_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query_by_id_response__pack
                     (const QueryByIdResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &query_by_id_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query_by_id_response__pack_to_buffer
                     (const QueryByIdResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &query_by_id_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QueryByIdResponse *
       query_by_id_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QueryByIdResponse *)
     protobuf_c_message_unpack (&query_by_id_response__descriptor,
                                allocator, len, data);
}
void   query_by_id_response__free_unpacked
                     (QueryByIdResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &query_by_id_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor query_by_id_response__field_descriptors[1] =
{
  {
    "employee",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(QueryByIdResponse, employee),
    &employee__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query_by_id_response__field_indices_by_name[] = {
  0,   /* field[0] = employee */
};
static const ProtobufCIntRange query_by_id_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor query_by_id_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "QueryByIdResponse",
  "QueryByIdResponse",
  "QueryByIdResponse",
  "",
  sizeof(QueryByIdResponse),
  1,
  query_by_id_response__field_descriptors,
  query_by_id_response__field_indices_by_name,
  1,  query_by_id_response__number_ranges,
  (ProtobufCMessageInit) query_by_id_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
