#ifndef MESSAGE_TYPES_H_
#define MESSAGE_TYPES_H_

// message type
enum EnMessageType
{
   MSG_INSERT_REQUEST = '0',
   MSG_INSERT_RESPONSE = '1',
   MSG_DELETE_REQUEST = '2',
   MSG_DELETE_RESPONSE = '3',
   MSG_QUERY_BY_ID_REQUEST = '4',
   MSG_QUERY_BY_ID_RESPONSE = '5',
   MSG_QUERY_BY_COMPENSATION_RANGE_REQUEST = '6',
   MSG_QUERY_BY_COMPENSATION_RANGE_RESPONSE = '7'
};

#define EMPLOYEE_NAME_SIZE 32

#endif /* MESSAGE_TYPES_H_ */
